name: CI/CD Pipeline

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python -m unittest discover tests
        
    - name: Deploy to Kubernetes
      if: github.ref == 'refs/heads/main'
      run: |
        echo ${{ secrets.KUBECONFIG }} | base64 --decode > kubeconfig.yaml
        kubectl apply -f k8s/deployment.yaml --kubeconfig=kubeconfig.yaml
        kubectl apply -f k8s/service.yaml --kubeconfig=kubeconfig.yaml
